apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: collection-app
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2NvbGxlY3Rpb25fdXNlcjpjb2xsZWN0aW9uX3Bhc3N3b3JkQHBvc3RncmVzLmNvbGxlY3Rpb24tYXBwLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzQvY29sbGVjdGlvbnM=
